### ISSUE TITLE
Cant sync to vault

### ISSUE THREAD

**Issue by srekkas** [robertlestak/cert-manager-sync#10]
Syncing to Vault doesnt work for me, have working certmanager issuing certs using Vault CA, which use Kubernetes auth too.
Error from cert-manager-sync pod.

> time="2024-06-18T08:26:08Z" level=error msg="vault.Login error" action=vault.Login authMethod=kubernetes error="Error making API request.\n\nURL: PUT http://vault.vault.svc.cluster.local:8200/v1/auth/kubernetes/login\nCode: 400. Errors:\n\n* missing jwt" role=cert-manager-sync vaultAddr="http://vault.vault.svc.cluster.local:8200"

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-sync-v1
  namespace: vault
  labels:
    app: cert-manager-sync
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-sync
      version: v1
  template:
    metadata:
      labels:
        app: cert-manager-sync
        version: v1
    spec:
      serviceAccountName: cert-manager-sync
      imagePullSecrets:
        - name: regcred
      containers:
        - image: robertlestak/cert-manager-sync:latest
          name: cert-manager-sync
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 5m
              memory: 16Mi
        - image: alpine:latest
          name: sidecar-tools
          command: ["/bin/sh", "-c", "tail -f /dev/null"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-sync
  namespace: vault
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-sync
  namespace: vault
subjects:
- kind: ServiceAccount
  name: cert-manager-sync
  namespace: vault
roleRef:
  kind: ClusterRole
  name: cert-manager-sync
  apiGroup: rbac.authorization.k8s.io
---
#https://developer.hashicorp.com/vault/docs/auth/kubernetes#configuring-kubernetes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:  
    name: role-tokenreview-binding
    namespace: vault
roleRef:  
    apiGroup: rbac.authorization.k8s.io     
    kind: ClusterRole  
    name: system:auth-delegator  
subjects:  
  - kind: ServiceAccount     
    name: cert-manager-sync
    namespace: vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-sync
  namespace: vault
```
